services:
  reservation-microservice:
    build: .
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://resrvationdb:3306/reservation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - resrvationdb

  resrvationdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_psw
      MYSQL_DATABASE: reservation_db
    ports:
      - "3340:3306"
